#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "UserService.pb.h"

namespace User
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void sign_up(UserRequest *request, UserResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void sign_in(UserRequest *request, UserResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using sign_upDone = std::function<void (UserResponse *, srpc::RPCContext *)>;
using sign_inDone = std::function<void (UserResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void sign_up(const UserRequest *req, sign_upDone done);
	void sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_up(const UserRequest *req);

	void sign_in(const UserRequest *req, sign_inDone done);
	void sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_in(const UserRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_sign_up_task(sign_upDone done);
	srpc::SRPCClientTask *create_sign_in_task(sign_inDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void sign_up(const UserRequest *req, sign_upDone done);
	void sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_up(const UserRequest *req);

	void sign_in(const UserRequest *req, sign_inDone done);
	void sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_in(const UserRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_sign_up_task(sign_upDone done);
	srpc::SRPCHttpClientTask *create_sign_in_task(sign_inDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void sign_up(const UserRequest *req, sign_upDone done);
	void sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_up(const UserRequest *req);

	void sign_in(const UserRequest *req, sign_inDone done);
	void sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_in(const UserRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_sign_up_task(sign_upDone done);
	srpc::BRPCClientTask *create_sign_in_task(sign_inDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void sign_up(const UserRequest *req, sign_upDone done);
	void sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_up(const UserRequest *req);

	void sign_in(const UserRequest *req, sign_inDone done);
	void sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_in(const UserRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_sign_up_task(sign_upDone done);
	srpc::TRPCClientTask *create_sign_in_task(sign_inDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void sign_up(const UserRequest *req, sign_upDone done);
	void sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_up(const UserRequest *req);

	void sign_in(const UserRequest *req, sign_inDone done);
	void sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> async_sign_in(const UserRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_sign_up_task(sign_upDone done);
	srpc::TRPCHttpClientTask *create_sign_in_task(sign_inDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("User")
{
	this->srpc::RPCService::add_method("sign_up",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::sign_up);
		});

	this->srpc::RPCService::add_method("sign_in",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::sign_in);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("User")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("User")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::sign_up(const UserRequest *req, sign_upDone done)
{
	auto *task = this->create_rpc_client_task("sign_up", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_up(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> SRPCClient::async_sign_up(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_up", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::sign_in(const UserRequest *req, sign_inDone done)
{
	auto *task = this->create_rpc_client_task("sign_in", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_in(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> SRPCClient::async_sign_in(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_in", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_sign_up_task(sign_upDone done)
{
	return this->create_rpc_client_task("sign_up", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_sign_in_task(sign_inDone done)
{
	return this->create_rpc_client_task("sign_in", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("User")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("User")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::sign_up(const UserRequest *req, sign_upDone done)
{
	auto *task = this->create_rpc_client_task("sign_up", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_up(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_sign_up(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_up", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::sign_in(const UserRequest *req, sign_inDone done)
{
	auto *task = this->create_rpc_client_task("sign_in", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_in(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_sign_in(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_in", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_sign_up_task(sign_upDone done)
{
	return this->create_rpc_client_task("sign_up", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_sign_in_task(sign_inDone done)
{
	return this->create_rpc_client_task("sign_in", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("User")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("User")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::sign_up(const UserRequest *req, sign_upDone done)
{
	auto *task = this->create_rpc_client_task("sign_up", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_up(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> BRPCClient::async_sign_up(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_up", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::sign_in(const UserRequest *req, sign_inDone done)
{
	auto *task = this->create_rpc_client_task("sign_in", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_in(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> BRPCClient::async_sign_in(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_in", srpc::RPCAsyncFutureCallback<UserResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_sign_up_task(sign_upDone done)
{
	return this->create_rpc_client_task("sign_up", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_sign_in_task(sign_inDone done)
{
	return this->create_rpc_client_task("sign_in", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("User")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("User")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::sign_up(const UserRequest *req, sign_upDone done)
{
	auto *task = this->create_rpc_client_task("/User/sign_up", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_up(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> TRPCClient::async_sign_up(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("/User/sign_up", srpc::RPCAsyncFutureCallback<UserResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::sign_in(const UserRequest *req, sign_inDone done)
{
	auto *task = this->create_rpc_client_task("/User/sign_in", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_in(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> TRPCClient::async_sign_in(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("/User/sign_in", srpc::RPCAsyncFutureCallback<UserResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_sign_up_task(sign_upDone done)
{
	auto *task = this->create_rpc_client_task("/User/sign_up", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_sign_in_task(sign_inDone done)
{
	auto *task = this->create_rpc_client_task("/User/sign_in", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("User")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("User")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::sign_up(const UserRequest *req, sign_upDone done)
{
	auto *task = this->create_rpc_client_task("sign_up", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::sign_up(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_up(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_sign_up(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_up", srpc::RPCAsyncFutureCallback<UserResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::sign_in(const UserRequest *req, sign_inDone done)
{
	auto *task = this->create_rpc_client_task("sign_in", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::sign_in(const UserRequest *req, UserResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_sign_in(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<UserResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_sign_in(const UserRequest *req)
{
	using RESULT = std::pair<UserResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<UserResponse>("sign_in", srpc::RPCAsyncFutureCallback<UserResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_sign_up_task(sign_upDone done)
{
	auto *task = this->create_rpc_client_task("sign_up", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_sign_in_task(sign_inDone done)
{
	auto *task = this->create_rpc_client_task("sign_in", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace User

